#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: runkharr@googlemail.com
# Copyright: (c) 2011, Boris Jakubith <runkharr@googlemail.com>
# Released under GPL v2.
#
# Small wrapper script for `cgen.c´ (compiles and executes it - via the `run´-command,
# which is also compiled on demand) ...
#

PROG="${0##*/}"
PPATH="${0%/*}"; if [ -z "$PATH" ]; then PATH=.; fi

if [ ! -x "$PPATH/run" -o "$PPATH/run.c" -nt "$PPATH/run" ]; then
    cc "$PPATH/run.c" -o "$PPATH/run"
fi
if [ ! -x "$PPATH/cgen.bin" -o "$PPATH/cgen.c" -nt "$PPATH/cgen.bin" ]; then
    cc "$PPATH/cgen.c" -o "$PPATH/cgen.bin"
fi

exec "$PPATH/run" "$PPATH/cgen.bin" as "$PPATH/cgen" ${1+"$@"}
