#! /bin/sh
#
# $Id: check_header,v 1.3 2008-01-24 00:47:12 bj Exp $
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: © 2005, Boris Jakubith <bj@isv-gmbh.de>
# Licence: GPL(v2)

prog="`basename "$0"`"

usage () {
    cat 1>&2 <<-EOT
    	Usage: ${prog} <header-filename> <macroname>
	EOT
    exit 0
}

if ! [ -d admin -a -f VERSION ]; then
    cat 1>&2 <<-EOT
	${prog}: you are probably in the wrong directory.
	EOT
    exit 64
fi

if ! [ -f admin/version -a -f Makefile ]; then
    cat 1>&2 <<-EOT
	${prog}: are you sure you are exceuting me in the right environment?
	EOT
    exit 64
fi

if [ $# -lt 2 ]; then usage; fi

header="$1"; shift
macname="$1"; shift
tsrc="${prog}-$$.c"
tobj="${prog}-$$.o"

cat >"$tsrc" <<-EOT
	#include <$header>

	int main () { return 0; }
	EOT

if cc -c "$tsrc" -o "$tobj" >/dev/null 2>&1; then
    rm -f "$tobj"; echo "-D${macname}=1"
fi

rm -f "$tsrc" "$tobj"

exit 0
