#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: fbj@blinx.de
# Copyright: (c) 2005-2009, Boris Jakubith <fbj@blinx.de>
# Licence: GPL (version 2)
#
# Utility for generating a source-archive from a (CVS-)source-tree of one of
# my programs ...
#

PROG="${0##*/}"

# Try an external binary first (if this file were installed somewhere) ...
#
progpath="`which "$PROG" >/dev/null 2>&1`"
if [ $? -eq 0 ]; then
    exec "$progpath" ${1+"$@"}
fi

# Now try to find a local binary version of this file ...
#
NOBIN=1
if [ -n "$NOBIN" ]; then
    if [ -f "$0.bin" -a -x "$0.bin" ]; then
	# binary version of this program exists ...
	if [ -f "$0.c" ]; then
	    # C-source of the binary program also exists ...
	    if [ "$0.c" -nt "$0.bin" ]; then
		# C-source is newer => re-generate binary program ...
		rm -f "$0.bin"; cc "$0.c" -o "$0.bin" >/dev/null 2>&1
	    fi
	else
	    # no C-source and we can't trust a binary only, so the binary is
	    # silently deleted ...
	    rm -f "$0.bin"
	fi
    elif [ -f "$0.c" ]; then
	# C-source exists => generate binary program ...
	cc "$0.c" -o "$0.bin" >/dev/null 2>&1
    fi

    # If the local binary (still) exists after all (re-)generating steps above,
    # it will be used for the further work ...
    #
    if [ -f "$0.bin" -a -x "$0.bin" ]; then
	exec "$0.bin" ${1+"$@"}
    fi
fi

if ! [ -d admin -a -f VERSION ]; then
    cat 1>&2 <<-EOT
	${prog}: you are probably in the wrong directory.
    	EOT
    exit 64
fi

if ! [ -f admin/version -a -f Makefile ]; then
    cat 1>&2 <<-EOT
	${prog}: are you sure you are exceuting me in the right environment?
	EOT
    exit 64
fi

VERSION=`cat VERSION`

usage () {
    cat <<-EOT
	Usage: $PROG [-v] bindist [-<arcmode>] install-prefix" 1>&2
	       $PROG [-v] srcdist [-<arcmode>]" 1>&2
	       $PROG

	arcmode:
	    gz, gzip
	       use a combination of 'tar' and 'gzip' for archiving
	    bz2, bzip2
	       use a combination of 'tar' and 'bzip2' for archiving
	    lzma
	       use a combination of 'tar' and 'lzma' for archiving
	    zip
	       use 'zip' for archiving
	    7z, 7zip
	       use '7z' for archiving
	EOT
    exit 0
}

vbegin () {
    if [ $VERBOSE -ne 0 ]; then
	echo "Creating $1 archive ($ARCMODE${COMPRESS+, }$COMPRESS)"
    else
	echo -n "Creating $1 archive "
    fi
}

vecho () {
    if [ $VERBOSE -ne 0 ]; then
	echo ${1+"$@"}
    else
	echo -n '.'
    fi
}

vdone () {
    if [ $VERBOSE -ne 0 ]; then
	echo "  archive file = $1"
	echo "done."
    else
	echo ". ($1) done."
    fi
}

# Escape the meta-characters used in a regular expression from the argument ...
#
escape_rx () {
    echo "$@" | sed -e 's,\(\[\|\]\|[$^.{}*+? \t]\),\\\1,g'
}

# Read the files/dirs to be excluded from the source distribution and print
# a single regular expressions (suitable as argument to the `-regex'-option of
# the `find'-command) from these files/dirs ...
#
#0#exclude_list () {
#0#    local save_IFS match cl f e res file="$1"
#0#    if [ -f "$file" ]; then
#0#	save_IFS="$IFS";
#0#	IFS=;
#0#	f="$file"
#0#	if [ "${f#/}" = "$f" -a "${f#./}" = "$f" -a "${f#../}" = "$f" ]; then
#0#	    f="./$f"
#0#	fi
#0#	res="`escape_rx "$f"`"
#0#	while read f; do
#0#	    # Check if the line is a comment line and skip it in this case ...
#0#	    cl="`echo "$f" | sed -e 's|^[ \t]*#.*$||'`"
#0#	    if [ -z "$cl" ]; then continue; fi
#0#
#0#	    # Prepend a './' if required (find prints pathes in this format) ...
#0#	    if [ "${f#/}" = "$f" -a "${f#./}" = "$f" -a "${f#../}" = "$f" ]
#0#	    then
#0#		f="./$f"
#0#	    fi
#0#
#0#	    # I don't allow reguilar expressions in the configuration file,
#0#	    # so the meta-characters are escaped here ...
#0#	    e="`escape_rx "$f"`"
#0#
#0#	    # Add a pattern for matching the path of a directory and all of
#0#	    # it's content ...
#0#	    if [ -d "$f" ]; then
#0#		e="`echo "$e" | sed -e 's,$,\\\(/.*\\\)\?,'`"
#0#	    fi
#0#
#0#	    # Append the resulting regular expression to the or'd list of
#0#	    # regular expressions which were already generated in the previous
#0#	    # steps ...
#0#	    res="$res\\|$e"
#0#	done < "$file"
#0#	IFS="$saveIFS"
#0#
#0#	# Print the or'd list of regular expressions, included in `^\(' and
#0#	# `$\)' ...
#0#	echo "^\\($res\\)\$"
#0#    fi
#0#}

VERBOSE=0; if [ $# -gt 0 -a "x$1" = "x-v" ]; then VERBOSE=1; shift; fi

if [ $# -lt 1 ]; then usage; fi

SFX=.tar; SF2=.gz
ARCMODE="tar cf"
COMPRESS="gzip -9f"

op="$1"; shift

if [ $# -gt 0 ]; then
    case $1 in
        -bz2|-bzip2)
            SFX=.tar; SF2=.bz2; ARCMODE="tar cf"; COMPRESS="bzip2 -9f"; shift
            ;;
        -gz|-gzip)
            SFX=.tar; SF2=.gz; ARCMODE="tar cf"; COMPRESS="gzip -9f"; shift
            ;;
        -zip)
            SFX=.zip; ARCMODE="zip -9rq"; unset COMPRESS SF2; shift
            ;;
	-lzma)
	    SFX=.tar; SF2=.lzma; ARCMODE="tar cf"; COMPRESS="lzma -9f"; shift
	    ;;
	-7z|-7zip)
	    SFX=.7z; ARCMODE="7z a -mx=9"; unset COMPRESS SF2
	    shift
	    ;;
        -*)
            echo "${0##*/}: unknown archive mode '$1'."; exit 64
            ;;
	*) ;;
    esac
fi
if [ "$op" = "bindist" -a $# -gt 0 ]; then
    pfx="PREFIX=$1"; shift
fi

case $op in
    srcdist)
	vbegin 'source'
	DISTDIR=`admin/version directory`
	vecho "  creating temporary directory"
	mkdir "$DISTDIR"
	vecho "  copying files"

	# Get the exclusion list ...
	EXCLUDE="`admin/exclude_list .srcdist-exclude`"
	if [ -n "$EXCLUDE" ]; then
	    # ... and convert it into a `find'-expression segment if it is
	    # not empty ...
	    EXCLUDE="-o \\( -regex '$EXCLUDE' \\) -prune"
	fi

	# Generate the `find'-command ...
	CMD="find . \( -path '*/CVS/*' -o -path '*/CVS' \) -prune -o \
	     \( -path './$DISTDIR/*' -o -path './$DISTDIR' \) -prune -o \
	     \( -path '*/.svn/*' -o -path '*/.svn' \) -prune \
	     $EXCLUDE -o -print \
	     | cpio -pdm '$DISTDIR' >/dev/null 2>&1"
	# and evaluate it ...
	eval "$CMD"
	vecho "  cleaning up directory"
	(cd "$DISTDIR"; make cleanall >/dev/null 2>&1)
	arcname="${DISTDIR}$SFX"
	atmp=.; abck=.; adir="$DISTDIR"
	;;
    bindist)
	vbegin 'binary'
	DISTDIR="`admin/version directory`.bin" 
	vecho "  creating temporary directory"
	mkdir "$DISTDIR"
	vecho "  binary install into temporary directory"
	if [ -z "$pfx" ]; then
	    if ! make "DESTDIR=$DISTDIR" install-root >/dev/null 2>&1; then
		make "DESTDIR=$DISTDIR" install >/dev/null 2>&1
	    fi
	else
	    if ! make "DESTDIR=$DISTDIR" "$pfx" install-root >/dev/null 2>&1
	    then
		make "DESTDIR=$DISTDIR" "$pfx" install >/dev/null 2>&1
	    fi
	fi
	arcname="${DISTDIR}$SFX"
	atmp="$DISTDIR"; abck=..; adir="."
	;;
    *)  usage ;;
esac

vecho "  archiving"
(cd "$atmp"; $ARCMODE >/dev/null "$abck/$arcname" "$adir")
carcname="${arcname}$SF2"
if [ -n "$COMPRESS" ]; then
    vecho "  compressing"
    $COMPRESS "$arcname"
fi
vecho "  removing temporary directory"
rm -rf "$DISTDIR"
vecho "  moving archive outside of `pwd`"
mv "$carcname" ..
vdone "../$carcname"
