#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: © 2005, Boris Jakubith <bj@isv-gmbh.de>
# Licence: GPL(v2)

# Mimic the behaviour of the `install'-command from the `fileutils'-package.

PROG="`basename $0`"

ask() {
    local p q
    if [ $# -lt 1 ]; then
	echo "${PROG}: missing argument for \`ask()'"; exit 64;
    fi
    while true; do
	echo -n "$1 "; read q
	if [ "x$q" = xyes -o "x$q" = xja ]; then return 0; fi
	if [ "x$q" = xno -o "x$q" = xnein ]; then return 1; fi
	echo "*** Please answer only with 'yes' ('ja') or 'no' ('nein')!"
	echo ''
    done
}

QUERY=0; strip=0

while [ $# -gt 0 ]; do
    case "$1" in
	-c) shift ;;
	-m*|-o*|-g*|-d*)
	    opt="`echo $1 | sed -e 's/\(-.\)/\1/'`"
	    xarg="`echo $1 | sed -e 's/^-.//'`"
	    if [ -z "$xarg" ]; then
		if [ $# -lt 1 ]; then
		    echo "$0: missing argument for option \`$opt'" 1>&2
		    exit 1
		fi
		shift; xarg="$1"
	    fi
	    shift
	    if [ "$opt" = "-m" ]; then mode="$xarg"
	    elif [ "$opt" = "-o" ]; then owner="$xarg"
	    elif [ "$opt" = "-g" ]; then group="$xarg"
	    elif [ "$opt" = "-d" ]; then mkdir="$xarg"
	    fi
	    ;;
	-q) QUERY=1; shift ;;
	-Q) QUERY=2; shift ;;
	-s) strip=1; shift ;;
	-z) compress=1; shift ;;
	-*) printf "%s%s\n%s\n" \
		"Usage: $0 [-c] [-m mode] [-o user] [-g group] [-s] " \
		"file... dirx" \
		"       $0 [-m mode] [-o user] [-g group] -d directory" \
		1>&2
	    exit 1
	    ;;
	*) break ;;
    esac
done

if [ -n "$mkdir" ]; then
    if [ $# -gt 0 ]; then
	printf "%s%s\n%s\n" \
	    "Usage: $0 [-c] [-m mode] [-o user] [-g group] [-s] " \
	    "file... dirx" \
	    "       $0 [-m mode] [-o user] [-g group] -d directory" \
	    1>&2
	exit 1
    fi
    mkdir -p "$mkdir" || exit 1
    if [ -n "$owner" ]; then chown "$owner" "$mkdir"; fi
    if [ -n "$group" ]; then chgrp "$group" "$mkdir"; fi
    if [ -n "$mode" ]; then chmod "$mode" "$mkdir"; fi
    exit 0
fi

if [ $# -lt 2 ]; then
    printf "%s%s\n%s\n" \
	"Usage: $0 [-c] [-m mode] [-o user] [-g group] [-s] " \
	"file... dirx" \
	"       $0 [-m mode] [-o user] [-g group] -d directory" \
	1>&2
    exit 1
fi

for i in "$@"; do OUT="$i"; done

if [ ! -d "$OUT" -a $# -gt 2 ]; then
    printf "%s%s\n" \
	"$0: if more than two arguments are given, the last one "
	"_must_ be a directory" 1>&2
    exit 1
fi

if [ ! -d "$OUT" ]; then
    nodel=0
    if [ -f "$OUT" -a $QUERY -ne 0 ]; then
	nodel=1
	if [ $QUERY -le 1 ]; then
	    if ask "Do you want to overwrite '$OUT'?"; then nodel=0; fi
	else
	    echo "*** Please check the file '$OUT'!";
	fi
    fi
    if [ $nodel -eq 0 ]; then
	rm -f "$OUT" || (echo 1>&2 "Removing '$OUT' failed"; exit 1)
	cp "$1" "$OUT"
	if [ $strip -ne 0 ]; then strip -- "$OUT"; fi
	if [ -n "$owner" ]; then chown "$owner" "$OUT"; fi
	if [ -n "$group" ]; then chgrp "$group" "$OUT"; fi
	if [ -n "$mode" ]; then chmod "$mode" "$OUT"; fi
    fi
    exit 0
fi

while [ $# -gt 1 ]; do
    bn="`basename $1`"; nodel=0
    if [ -f "$OUT/$bn" -a $QUERY -ne 0 ]; then
	nodel=1
	if [ $QUERY -le 1 ]; then
	    if ask "Do you want to overwrite '$OUT/$bn'?"; then nodel=0; fi
	else
	    echo "*** Please check the file '$OUT/$bn'!";
	fi
    fi
    if [ $nodel -eq 0 ]; then
	rm -f "$OUT/$bn" || (echo 1>&2 "Removing '$OUT/$bn' failed"; exit 1)
	cp "$1" "$OUT"
	if [ -n "$owner" ]; then chown "$owner" "$OUT/$bn"; fi
	if [ -n "$group" ]; then chgrp "$group" "$OUT/$bn"; fi
	if [ -n "$mode" ]; then chmod "$mode" "$OUT/$bn"; fi
	if [ $strip -ne 0 ]; then strip -- "$OUT/$bn"; fi
	if [ -n "$compress" ]; then gzip -9f "$OUT/$bn"; fi
    fi
    shift
done
