#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: © 2008, Boris Jakubith <fbj@blinx.de>
# Licence: GPL(v2)

abspath() {
    local pn="$1"
    if [ "${pn#/}" == "$pn" ]; then
	pn="$(cwd)/${pn#./}"; pn="${pn//\/\//\/}"; pn="${pn%/}"
    fi
    # Absolute PATH
    pn="${pn%/*}"; : ${pn:=/}
    echo "$pn"
}

dirname() {
    if [ "x$1" = x. ]; then
	echo 1>&2 "${PROG}: dirname() - invalid argument"; exit 1
    fi
    local pn="${1%/*}"
    if [ "x$pn" = "x$1" ]; then
	pn=.; if [ "x${1#/}" != "x$1" ]; then pn=/; fi
    fi
    echo $pn
}

usage() {
    if [ $# -gt 0 ]; then echo 1>&2 "${PROG}:" "$@"; exit 64; fi
    cat <<-EOT
	Usage: ${PROG} [-q] [-m fmask] daemon-path init-path
	       ${PROG} -h
	EOT
    exit 0
}

lxdist() {
    if [ -f /etc/issue.net ]; then
	head -1 /etc/issue.net | cut -d' ' -f1 | tr 'A-Z' 'a-z'
    elif [ -f /etc/issue ]; then
	head -1 /etc/issue | cut -d' ' -f1 | tr 'A-Z' 'a-z'
    else
	echo unknown
    fi
}

PROG="${0##*/}"
PPATH="$(abspath "$(dirname "$0")")";

top="$(dirname "$PPATH")";
cd "$top"

LXDIST=$(lxdist)

mode=0755
OPTS=
while [ $# -gt 0 ]; do
    case "$1" in
	-q|-Q)  OPTS="$OPTS $1"; shift ;;
	-m*) OPTS="$OPTS $1"
	     mode=`expr "$1" : '-m\(.*\)'`
	     if [ "x$mode" = x ]; then
		 if [ $# -lt 2 ]; then
		    usage "missing argument for option '-m'"
		 fi
		 shift; OPTS="$OPTS $1"; mode="$1"
	     fi
	     shift
	     ;;
	-h)  usage ;;
	--)  shift; break ;;
	-*)  usage "invalid option '$1'" ;;
	*)   break ;;
    esac
done

if [ $# -lt 2 ]; then
    usage "missing argument(s); try '${PROG} -h' for help, please!"
fi

daemon="$(abspath "$1")"; shift
init="$(abspath "$1")"; shift

if [ -d "$init" ]; then
    initname="${daemon##*/}"
    init="$init/$initname"
else
    dn="$(dirname "$init")"
    if ! [ -d "$dn" ]; then
	initname="${init##*/}"
    fi
    mkdir -p "$dn"
fi

name="${daemon##*/}"
dmdir="$(dirname "$daemon")"
prefix="$(dirname "$(abspath "$dmdir")")"
initp="initd/$LXDIST"

sed <"$initp" >"$init" \
    -e "s|%NAME%|$name|g; s|%PREFIX%|$prefix|g; s|%DAEMON%|$daemon|g" \
    -e "s|%INITNAME%|$initname|g; s|%DESC%|service|g" \
    -e "s|%DATE%|`date +%d-%b-%Y`|g" 
    

chmod a+x "$init"
