#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: runkharr@googlemail.com
# Copyright: (c) 2011, Boris Jakubith <runkharr@googlemail.com>
# Released under GPL v2.
#
# Small wrapper script for a `.c´-file with the same basename (compiles and
# executes it - via the `run´-command, which is also compiled on demand) ...
#

PROG="${0##*/}"
PPATH="${0%/*}"; if [ -z "$PATH" ]; then PATH=.; fi

if ! type >/dev/null cc; then
    echo 1>&2 "${PROG}: 'cc' not found - can't continue!"; exit 1
fi

if [ ! -x "$PPATH/run" -o "$PPATH/run.c" -nt "$PPATH/run" ]; then
    if ! cc "$PPATH/run.c" -o "$PPATH/run"; then
        echo 1>&2: "${PROG}: couldn't generate 'run'!"; exit 1
    fi
fi
if [ ! -x "$PPATH/${PROG}.bin" -o "$PPATH/${PROG}.c" -nt "$PPATH/${PROG}.bin" ]
then
    if ! cc "$PPATH/${PROG}.c" -o "$PPATH/${PROG}.bin"; then
        echo 1>&2: "${PROG}: couldn't generate '${PROG}.bin'!"; exit 1
    fi
fi

exec "$PPATH/run" "$PPATH/${PROG}.bin" as "$PPATH/${PROG}" ${1+"$@"}
