#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: runkharr@googlemail.com
# Copyright: (c) 2011, Boris Jakubith <runkharr@googlemail.com>
# Released under GPL v2.
#
# Small wrapper script for a `.c´-file with the same basename (compiles and
# executes it - via the `run´-command, which is also compiled on demand) ...
#

PROG="${0##*/}"
PPATH="${0%/*}"; if [ -z "$PATH" ]; then PATH=.; fi

# Being paranoid!
export PATH; PATH=/usr/local/bin:/usr/pkg/bin:/usr/bin:/bin

# Check if a program named `cc´ (probably the C-compiler) exists.
# (If `cc´ exists but is no C-compiler, the complete script may fail because
#  of the wrong calling conventions ...)
if ! type >/dev/null cc; then
    echo 1>&2 "${PROG}: 'cc' not found - can't continue!"; exit 1
fi

# Check for two programs and try to (re-)generate them (from the corresponding
# `.c´ source files) if necessary ...
for bn in run "$PROG"; do
    # Shorthands for source and binary file (makes the following less
    # error-prone) ...
    cf="$PPATH/$bn.c"; bf="$PPATH/$bn.bin"

    # It is always an error if the source file doesn't exist!
    if [ ! -f "$cf" ]; then
	echo 1>&2 "${PROG}: required '$cf' doesn't exist or is no plain file"
	exit 1
    fi

    # If the `binary´ file exists but is either not a plain file or not
    # an executable, delete it.
    if [ -e "$bf" ] && [ ! -f "$bf" -o ! -x "$bf" ]; then
	# Deleting a directory is strictly forbidden!
	if [ -d "$bf" ]; then
	    echo 1>&2 "${PROG}: target file '$bf' is a directory"; exit 1
	fi
	rm -f "$bf"
    fi

    # If the binary file doesn't exist or is not executable, or if the source
    # file is newer than the binary file, try to (re-)generate the binary from
    # the source - using the program `cc´ (probably a C-compiler).
    if [ ! -x "$bf" -o "$cf" -nt "$bf" ]; then
	if ! cc -I"$PPATH" "$cf" -o "$bf"; then
	    echo 1>&2 "${PROG}: couldn't generate '$bf'!"; exit 1
	fi
    fi
done

# Now execute the binary file (under the control of `run´, which fixes it's
# argv[0] - the program's pathname).
exec "$PPATH/run.bin" "$PPATH/${PROG}.bin" as "$PPATH/${PROG}" ${1+"$@"}
