#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: runkharr@googlemail.com
# Copyright: (c) 2011, Boris Jakubith <runkharr@googlemail.com>
# Released under GPL v2.
#
# Small wrapper script for a `.c´-file with the same basename (compiles and
# executes it - via the `run´-command, which is also compiled on demand) ...
#

PROG="${0##*/}"
PPATH="$(realpath "$(dirname "$0")")"

# Being paranoid!
export PATH; PATH=/usr/local/bin:/usr/pkg/bin:/usr/bin:/bin

if [ -n "$DEBUG" ]; then
    case "$DEBUG" in
	(y|yes|1|true|t|j|ja) GO=-g ;;
    esac
fi

# Check if a program named `cc´ (probably the C-compiler) exists.
# (If `cc´ exists but is no C-compiler, the complete script may fail because
#  of the wrong calling conventions ...)
if ! type >/dev/null cc; then
    echo 1>&2 "${PROG}: 'cc' not found - can't continue!"; exit 1
fi

add_ppath() {
    ap_f="$1"
    ap_isv="$IFS"; IFS=' 	'
    ap_files=$(cat "$ap_f")
    for ap_x in $ap_files; do
	if [ "${ap_x#/}" = "$ap_x" ]; then
	    echo "$PPATH/$ap_x"
	else
	    echo "$ap_x"
	fi
    done
    IFS="$ap_isv"
}

EXTRA_MODS=
if [ -f "$PPATH/xmods/$PROG" ]; then
    EXTRA_MODS="$(add_ppath "$PPATH/xmods/$PROG")"
fi

# NEW! Build the binary in the given directory/with the given filename
# instead of executing it ...
if [ $# -gt 0 ] && [ "$1" = --build ]; then
    shift
    if [ $# -lt 1 ]; then
	echo 1>&2 "${PROG}: Need a target-path for building '$bn'"; exit 1
    fi
    tgt="$1"; shift; cf="$PPATH/$PROG.c"
    if [ ! -f "$cf" ]; then
	echo 1>&2 "${PROG}: required '$cf' doesn't exist or is no plain file"
	exit 1
    fi
    if [ -d "$tgt" ]; then
	tgt="$tgt/$PROG"
    elif [ -e "$tgt" ] && { [ -h "$tgt" ] || [ ! -f "$tgt" ]; }; then
	echo 1>&2 "${PROG}; Target exists and is no regular file"; exit 1
    fi
    tp=; if [ -e "$tgt" ]; then tp="$(stat -c '%d:%i' "$tgt")"; fi
    me="$(stat -c '%d:%i' "$0")"
    if [ "$me" = "$tp" ]; then
	echo 1>&2 "${PROG}: Using me ($0) as target is illegal"; exit 1
    fi
    # shellcheck disable=SC2086
    exec cc -I$PPATH "$cf" $EXTRA_MODS "$GO" -o "$tgt"
fi
	

# Check for two programs and try to (re-)generate them (from the corresponding
# `.c´ source files) if necessary ...
for bn in run "$PROG"; do
    # Shorthands for source and binary file (makes the following less
    # error-prone) ...
    cf="$PPATH/$bn.c"; bf="$PPATH/$bn.bin"

    # It is always an error if the source file doesn't exist!
    if [ ! -f "$cf" ]; then
	echo 1>&2 "${PROG}: required '$cf' doesn't exist or is no plain file"
	exit 1
    fi

    # If the `binary´ file exists but is either not a plain file or not
    # an executable, delete it.
    if [ -e "$bf" ] && { [ ! -f "$bf" ] || [ ! -x "$bf" ]; }; then
	# Deleting a directory is strictly forbidden!
	if [ -d "$bf" ]; then
	    echo 1>&2 "${PROG}: target file '$bf' is a directory"; exit 1
	fi
	rm -f "$bf"
    fi

    # If the binary file doesn't exist or is not executable, or if the source
    # file is newer than the binary file, try to (re-)generate the binary from
    # the source - using the program `cc´ (probably a C-compiler).
    test "$bn" = run && extras= || extras="$EXTRA_MODS"
    if [ ! -x "$bf" ] || [ "$cf" -nt "$bf" ] || [ "$0" -nt "$bf" ]; then
	# shellcheck disable=SC2086
	if ! cc -I"$PPATH" "$cf" $extras "$GO" -o "$bf"; then
	    echo 1>&2 "${PROG}: couldn't generate '$bf'!"; exit 1
	fi
    fi
done

# Now execute the binary file (under the control of `run´, which fixes it's
# argv[0] - the program's pathname).
exec "$PPATH/run.bin" "$PPATH/${PROG}.bin" as "$PPATH/${PROG}" ${1+"$@"}
