#! /bin/sh
#
# admin/srcdist		- program for generating a non-CVS archive from a
#              		  source tree
#
# $Id: srcdist,v 1.3 2005-11-22 08:05:20 bj Exp $
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: 2005, Boris Jakubith <bj@isv-gmbh.de>
# Licence: GPL(v2)
# 


SFX=.tar
ARCMODE="tar cf"
COMPRESS="gzip -9f"
if [ $# -ge 1 ]; then
    case $1 in
	bz2|bzip2)
	    SFX=.tar; ARCMODE="tar cf"; COMPRESS="bzip2 -9f"; shift
	    ;;
	gz|gzip)
	    SFX=.tar; ARCMODE="tar cf"; COMPRESS="gzip -9f"; shift
	    ;;
	zip)
	    SFX=.zip; ARCMODE="zip -9rq"; unset COMPRESS; shift
	    ;;
	*)
	    echo "${0##*/}: unknown archive mode '$1'."; exit 64
	    ;;
    esac
fi

echo "Creating srcdist ($ARCMODE${COMPRESS+, }$COMPRESS)"

DISTDIR=`admin/version directory`

if [ -e "$DISTDIR" ]; then rm -rf "$DISTDIR"; fi

echo "  creating directory"
mkdir "$DISTDIR"

echo "  copying files"
find . \( -path '*/CVS/*' -o -path '*/CVS' \) -prune -o \
       \( -path "./$DISTDIR/*" -o -path "./$DISTDIR" \) -prune -o \
       -print \
| cpio -pdm "$DISTDIR" >/dev/null 2>&1


echo "  archiving"
$ARCMODE "${DISTDIR}$SFX" "$DISTDIR"
if [ -n "$COMPRESS" ]; then
    echo "  compressing"
    $COMPRESS "${DISTDIR}$SFX"
fi
echo "  removing directory"
rm -rf "$DISTDIR"
echo "  moving archive outside of `pwd`"
mv "${DISTDIR}$SFX"* ..
echo "done."
