#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: © 2005, Boris Jakubith <bj@isv-gmbh.de>
# Licence: GPL(v2)

prog="$0"
fp="${0%/*}/fullpath"
ppath="`$fp -b1 "$0"`"
top=`expr "$ppath" : '\(.\+\)/admin'`

cd "$top"

usage () {
    cat 1>&2 <<-EOT
	Usage: $prog {get|set|major|ostype|lxdist}
	       $prog [binary-|source]directory
	       $prog header <.h-file>
	       $prog packagename
	EOT
    exit 64
}

newVersion() {
    local ans new cut
    echo "The current version is $VERSION ."
    echo -n "Do you want to change it? "
    ans=x
    while [ "$ans" = x ]; do
	read ans;
	case $ans in
	    y|ye|yes|j|ja)    ans=y ;;
	    n|no|ne|nei|nein) ans=n ;;
	    *)
		ans=x
		echo -n "Do you want to change it? "
		;;
	esac
    done
    if [ "$ans" = n ]; then return; fi
    echo
    echo -n "Please enter the new version number: "
    ans=x
    while [ "$ans" = x ]; do
	read new
	cut="`echo $new|sed -e 's/\([0-9]\{1,2\}\.[0-9]\{1,2\}\(-[0-9a-zA-Z]\+\)\?\)//'`"
	if [ -z "$cut" ]; then
	    ans=
	else
	    echo "+++ INVALID version string - please retry!"
	    echo
	    echo -n "Please enter the new version number: "
	    ans=x
	fi
    done
    echo $new >"$top/VERSION"
    echo "OK, version number is now: $new"
}

if ! [ -d admin -a -f "$top/VERSION" ]; then
    echo 1>&2 "${prog}: you are probably in the wrong directory"
    exit 64
fi

# Get the version number from the `VERSION´ file in the top-level directory ...
#
VERSION="`cat "$top/VERSION"`"

case $1 in
    directory|srcdir|source-directory)
	pwd=`pwd`; wd=`basename "$pwd"`
	VS="`echo \"$VERSION\" | sed -e 's/\([.\\|]\)/\\\\\1/g'`"
	wd="`echo \"$wd\" | sed -e \"s|-$VS\$||\"`"
	echo "${wd}-$VERSION"
	;;
    bindir|binary-directory)
	pwd=`pwd`; wd=`basename "$pwd"`
	VS="`echo \"$VERSION\" | sed -e 's/\([.\\|]\)/\\\\\1/g'`"
	wd="`echo \"$wd\" | sed -e \"s|-$VS\$||\"`"
	echo "${wd}-$VERSION-bin"
	;;
    get)
	echo "$VERSION"
	;;
    set)
	newVersion
	;;
    major)
	expr $VERSION : '\([0-9]*\)\..*'
	;;
    ostype)
	ostype=`uname -s`
	case $ostype in
	    MINGW32*)
		echo 'MINGW32' ;;
	    *)
		echo $ostype ;;
	esac
	;;
    lxdist)
	if ! [ -f /etc/issue ]; then echo unknown
	elif fgrep -i 'Debian' /etc/issue >/dev/null 2>&1; then echo Debian
	elif fgrep -i 'SuSE' /etc/issue >/dev/null 2>&1; then echo SuSE
	elif fgrep -i 'Red Hat' /etc/issue >/dev/null 2>&1; then echo RedHat
	elif fgrep -i 'Trustix' /etc/issue >/dev/null 2>&1; then echo Trustix
	else echo unknown
	fi
	;;
    header)
	if [ $# -lt 2 ]; then
	    echo "Usage: `basename $0` header <.h-file>" 1>&2; exit 64
	fi
	cat >$2 <<-EOT
		/* version.h
		**
		** automatically created file
		** PLEASE DO NOT EDIT!
		**
		*/
		#ifndef _VERSION_H
		#define _VERSION_H
		
		#define VERSION "${VERSION}"
		
		#endif /* defined(_VERSION_H) */
		EOT
	;;
    packagename|pkgname|package|name)
	if [ -f "$top/PACKAGE" ]; then
	    sname="`head -1 "$top/PACKAGE" | tr ' [A-Z]_' '-[a-z]-'`"
	else
	    sname="${top##*/}"
	    sname="${sname%-${VERSION}}"
	    sname="`echo "$sname"|tr ' [A-Z]_' '-[a-z]-'`"
	fi
	echo "$sname"
	;;
    *)
	usage
	;;
esac
