#! /bin/sh
#
# $Id$
#
# Author: Boris Jakubith
# E-Mail: bj@isv-gmbh.de
# Copyright: © 2005, Boris Jakubith <bj@isv-gmbh.de>
# Licence: GPL(v2)

prog="$0"
fp="${0%/*}/fullpath"
ppath="`$fp -b1 "$0"`"
adm=`echo "$ppath" | sed -e 's|/admin||'`

#cwd=`pwd`
#test -f "$cwd/VERSION" && top="$cwd" || cd "$top"

usage() {
    cat 1>&2 <<-EOT
	Usage: $prog {get|set|major|minor|number|ostype|lxdist}
	       $prog [binary-|source-]directory
	       $prog header <.h-file>
	       $prog packagename
	EOT
    exit 64
}

eecho() {
    echo 1>&2 ${1+"$@"}
}

newVersion() {
    local ans new cut
    echo "The current version is $VERSION ."
    echo -n "Do you want to change it? "
    ans=x
    while [ "$ans" = x ]; do
	read ans;
	case $ans in
	    y|ye|yes|j|ja)    ans=y ;;
	    n|no|ne|nei|nein) ans=n ;;
	    *)
		ans=x
		echo -n "Do you want to change it? "
		;;
	esac
    done
    if [ "$ans" = n ]; then return; fi
    echo
    echo -n "Please enter the new version number: "
    ans=x
    while [ "$ans" = x ]; do
	read new
	cut="`echo $new|sed -e 's/\([0-9]\{1,2\}\.[0-9]\{1,2\}\(-[0-9a-zA-Z]\+\)\?\)//'`"
	if [ -z "$cut" ]; then
	    ans=
	else
	    echo "+++ INVALID version string - please retry!"
	    echo
	    echo -n "Please enter the new version number: "
	    ans=x
	fi
    done
    echo $new >"$top/VERSION"
    echo "OK, version number is now: $new"
}

newTop() {
    local dn="$1" wd="`pwd`"
    cd "$dn" || { eecho "${PROG}: chdir into '$dn' failed"; exit 1; }
    dn="`pwd`"
    echo "$dn"
}

keepTop() {
    local cwd="`pwd`"
    test -f "$cwd/VERSION" && top="$cwd" || top="$adm"
    cd "$top"
}

# Get the version number from the `VERSION´ file in the top-level directory ...
#
initVersion() {
    if [ -f "$top/VERSION" ]; then
	VERSION="`cat "$top/VERSION"`"
    elif [ -d "$adm/admin" ]; then
	VERSION='0.01'
	eecho "${prog}: Creating initial VERSION file; content: $VERSION"
	echo >"$top/VERSION" "$VERSION"
    else
	eecho "${prog}: you are probably in the wrong directory"
	exit 64
    fi
}
    

case $1 in
    directory|srcdir|source-directory)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	pwd=`pwd`; wd=`basename "$pwd"`
	VS="`echo \"$VERSION\" | sed -e 's/\([.\\|]\)/\\\\\1/g'`"
	wd="`echo \"$wd\" | sed -e \"s|-$VS\$||\"`"
	echo "${wd}-$VERSION"
	;;
    bindir|binary-directory)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	pwd=`pwd`; wd=`basename "$pwd"`
	VS="`echo \"$VERSION\" | sed -e 's/\([.\\|]\)/\\\\\1/g'`"
	wd="`echo \"$wd\" | sed -e \"s|-$VS\$||\"`"
	echo "${wd}-$VERSION-bin"
	;;
    get|number)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	echo "$VERSION"
	;;
    set)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	newVersion
	;;
    major)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	expr $VERSION : '\([0-9]*\)\..*'
	;;
    minor)
	if [ $# -gt 1 ]; then top="$(newTop "$2")"; else keepTop; fi
	initVersion
	echo "$VERSION" | sed -e 's/^[0-9]\+\.\(.\+\)/\1/'
	;;
    ostype)
	ostype=`uname -s`
	case $ostype in
	    MINGW32*)
		echo 'MINGW32' ;;
	    *)
		echo $ostype ;;
	esac
	;;
    lxdist)
	if [ -f /etc/issue.net ]; then
	    head -1 /etc/issue.net | cut -d' ' -f1
	elif [ -f /etc/issue ]; then
	    head -1 /etc/issue | cut -d' ' -f1
	else
	    echo unknown
	fi
	;;
    header)
	if [ $# -lt 2 ]; then
	    echo "Usage: `basename $0` header <.h-file>" 1>&2; exit 64
	fi
	if [ $# -gt 2 ]; then top="$(newTop "$3")"; else keepTop; fi
	initVersion
	if [ "${2#/}" != "$2" ]; then vhf="$2"; else vhf="$cwd/$2"; fi
	if [ -e "$vhf" ]; then echo "${prog}: '$vhf' already exists"; exit 1; fi
	cat >"$vhf" <<-EOT
		/* version.h
		**
		** automatically created file
		** PLEASE DO NOT EDIT!
		**
		*/
		#ifndef VERSION_H
		#define VERSION_H
		
		#define VERSION "${VERSION}"
		
		#endif /* defined(VERSION_H) */
		EOT
	;;
    packagename|pkgname|package|name)
	if [ $# -gt 2 ]; then top="$(newTop "$3")"; else keepTop; fi
	initVersion
	if [ -f "$top/PACKAGE" ]; then
	    sname="`head -1 "$top/PACKAGE" | tr ' [A-Z]_' '-[a-z]-'`"
	else
	    sname="${top##*/}"
	    sname="${sname%-${VERSION}}"
	    sname="`echo "$sname"|tr ' [A-Z]_' '-[a-z]-'`"
	fi
	echo "$sname"
	;;
    *)
	usage
	;;
esac
